# Generated by Django 5.1.3 on 2024-11-25 15:22

import sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='transaction_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
