# Generated by Django 5.1.3 on 2024-11-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_sale_item_remove_sale_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
