# Generated by Django 5.1.3 on 2024-11-25 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_is_returned_sale_return_date_sale_return_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.saleitem')),
            ],
        ),
    ]
