# Generated by Django 5.1.2 on 2024-11-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_customuser_role"),
        ("inventory", "0006_remove_warehouse_user_warehouse_users_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="warehouses",
            field=models.ManyToManyField(blank=True, to="inventory.warehouse"),
        ),
    ]
