# Generated by Django 5.0.9 on 2024-12-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_customuser_warehouses"),
        ("inventory", "0007_globalsettings_inventoryitem_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("attendance", "Attendance"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="warehouses",
            field=models.ManyToManyField(
                related_name="custom_users", to="inventory.warehouse"
            ),
        ),
    ]
