# Generated by Django 5.1.2 on 2024-11-01 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0003_brand_category_alter_inventoryitem_brand_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Requisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requisition_type",
                    models.CharField(
                        choices=[("PRODUCT", "Product"), ("LABOR", "Labor")],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED_BY_MANAGER", "Approved by Manager"),
                            ("REJECTED_BY_MANAGER", "Rejected by Manager"),
                            ("APPROVED_BY_ADMIN", "Approved by Admin"),
                            ("REJECTED_BY_ADMIN", "Rejected by Admin"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("manager_comment", models.TextField(blank=True, null=True)),
                ("admin_comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
