# Generated by Django 5.1.2 on 2024-11-01 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_brand_category_alter_inventoryitem_brand_and_more"),
        ("requisition", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="requisition",
            old_name="description",
            new_name="reason",
        ),
        migrations.RemoveField(
            model_name="requisition",
            name="admin_comment",
        ),
        migrations.RemoveField(
            model_name="requisition",
            name="manager_comment",
        ),
        migrations.RemoveField(
            model_name="requisition",
            name="requisition_type",
        ),
        migrations.AlterField(
            model_name="requisition",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved_by_manager", "Approved by Manager"),
                    ("rejected_by_manager", "Rejected by Manager"),
                    ("approved_by_admin", "Approved by Admin"),
                    ("rejected_by_admin", "Rejected by Admin"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
