# Generated by Django 5.1.2 on 2024-11-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requisition", "0002_rename_description_requisition_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requisition",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved_by_manager", "Approved by Manager"),
                    ("rejected_by_manager", "Rejected by Manager"),
                    ("pending_admin_approval", "Pending Admin Approval"),
                    ("approved_by_admin", "Approved by Admin"),
                    ("rejected_by_admin", "Rejected by Admin"),
                ],
                default="pending",
                max_length=25,
            ),
        ),
    ]
