# Generated by Django 5.1.2 on 2024-11-01 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_brand_category_alter_inventoryitem_brand_and_more"),
        ("requisition", "0003_alter_requisition_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisition",
            name="labor_service_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="requisition",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("item", "Item Request"),
                    ("labor_service", "Labor/Service Request"),
                ],
                default="item",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.inventoryitem",
            ),
        ),
    ]
