# Generated by Django 5.1.2 on 2024-11-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requisition", "0004_requisition_labor_service_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requisition",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
