# Generated by Django 5.1.2 on 2024-11-02 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_warehouse_inventoryitem_warehouse"),
        ("requisition", "0005_alter_requisition_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisition",
            name="approval_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="requisition",
            name="destination_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_requisitions",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="requisition",
            name="source_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_requisitions",
                to="inventory.warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved_by_manager", "Approved by Manager"),
                    ("rejected_by_manager", "Rejected by Manager"),
                    ("pending_admin_approval", "Pending Admin Approval"),
                    ("approved_by_admin", "Approved by Admin"),
                    ("rejected_by_admin", "Rejected by Admin"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                ],
                default="pending",
                max_length=25,
            ),
        ),
    ]
