# Generated by Django 5.1.2 on 2024-11-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requisition", "0006_requisition_approval_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requisition",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="request_type",
            field=models.CharField(
                choices=[("item", "Item"), ("labor_service", "Labor/Service")],
                default="item",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("pending_admin_approval", "Pending Admin Approval"),
                    ("approved_by_admin", "Approved by Admin"),
                    ("rejected_by_manager", "Rejected by Manager"),
                    ("rejected_by_admin", "Rejected by Admin"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=25,
            ),
        ),
    ]
