# Generated by Django 5.1.3 on 2024-11-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0007_alter_requisition_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='manager_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
