# Generated by Django 5.1.3 on 2024-11-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0008_requisition_manager_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='actual_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='delivered_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='delivery_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='estimated_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_admin_approval', 'Pending Admin Approval'), ('approved_by_admin', 'Approved by Admin'), ('in_delivery', 'In Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('rejected_by_manager', 'Rejected by Manager'), ('rejected_by_admin', 'Rejected by Admin')], default='pending', max_length=25),
        ),
    ]
