# Generated by Django 5.1.3 on 2024-11-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0010_requisition_description_alter_requisition_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='delivery_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_images/'),
        ),
    ]
