# Generated by Django 5.1.3 on 2024-12-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0013_remove_requisition_delivered_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Manager Approval'), ('approved', 'Approved by Manager'), ('rejected', 'Rejected by Manager'), ('in_delivery', 'In Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed')], default='pending', max_length=25),
        ),
    ]
