# Generated by Django 5.1.3 on 2024-12-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0014_alter_requisition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='actual_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending_delivery', 'Pending Delivery'), ('in_delivery', 'In Delivery'), ('received', 'Received'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=25),
        ),
    ]
