# Generated by Django 5.1.3 on 2024-12-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0016_requisitionitem_selected_source_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='labor_service_description',
        ),
        migrations.AlterField(
            model_name='requisition',
            name='request_type',
            field=models.CharField(choices=[('item', 'Item Request'), ('labor_service', 'Labor/Service Request')], default='item', max_length=20),
        ),
    ]
