# Generated by Django 5.0.9 on 2024-12-17 21:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requisition", "0021_alter_deliveryitem_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="delivery_comment",
        ),
        migrations.AddField(
            model_name="delivery",
            name="additional_docs",
            field=models.FileField(blank=True, null=True, upload_to="delivery_docs/"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_receipt",
            field=models.FileField(
                blank=True, null=True, upload_to="delivery_receipts/"
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="delivered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="delivery_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="estimated_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="requisition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="requisition.requisition",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_delivery", "Pending Delivery"),
                    ("in_delivery", "In Delivery"),
                    ("pending_admin", "Pending Admin Confirmation"),
                    ("received", "Received"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending_delivery",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_delivery", "Pending Delivery"),
                    ("in_delivery", "In Delivery"),
                    ("pending_admin", "Pending Admin Confirmation"),
                    ("received", "Received"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending_delivery",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("pending_admin_approval", "Pending Admin Approval"),
                    ("approved_by_admin", "Approved by Admin"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("pending_delivery", "Pending Delivery"),
                    ("in_delivery", "In Delivery"),
                    ("received", "Received"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=25,
            ),
        ),
    ]
