# Generated by Django 5.0.9 on 2024-12-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requisition", "0022_remove_delivery_delivery_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="delivery_personnel_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_personnel_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_personnel_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
