# Generated by Django 5.0.9 on 2024-12-18 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("requisition", "0023_delivery_delivery_personnel_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="delivery_personnel_email",
        ),
    ]
