# Generated by Django 5.0.9 on 2024-12-19 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requisition", "0025_delivery_delivery_image_alter_delivery_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequisitionStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("pending_admin_approval", "Pending Admin Approval"),
                            ("approved_by_admin", "Approved by Admin"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("pending_delivery", "Pending Delivery"),
                            ("in_delivery", "In Delivery"),
                            ("received", "Received"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=25,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requisition.requisition",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Requisition Status Histories",
                "ordering": ["-timestamp"],
            },
        ),
    ]
