# Generated by Django 5.0.9 on 2024-12-19 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requisition", "0026_requisitionstatushistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="requisitionstatushistory",
            options={"verbose_name_plural": "Requisition Status Histories"},
        ),
        migrations.AlterField(
            model_name="requisitionstatushistory",
            name="requisition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="requisition.requisition",
            ),
        ),
    ]
