# Generated by Django 5.0.9 on 2024-12-20 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requisition", "0027_alter_requisitionstatushistory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="delivery_personnel_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_phone",
                        message='Phone number must be 11 digits and start with either "63" or "09"',
                        regex="^(63|09)\\d{9}$",
                    )
                ],
            ),
        ),
    ]
