# Generated by Django 5.1.4 on 2024-12-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0029_merge_20231225_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisition',
            options={'permissions': [('can_approve_requisition', 'Can approve requisition')]},
        ),
    ]
