# Generated by Django 5.1.2 on 2024-11-02 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_warehouse_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouse",
            name="user",
        ),
        migrations.AddField(
            model_name="warehouse",
            name="users",
            field=models.ManyToManyField(
                related_name="warehouses", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.brand"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.category",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="stock",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.warehouse",
            ),
        ),
    ]
