# Generated by Django 5.1.3 on 2024-11-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
        ('requisition', '0011_requisition_delivery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='requisitions',
            field=models.ManyToManyField(blank=True, related_name='purchase_orders', to='requisition.requisition'),
        ),
    ]
