# Generated by Django 5.1.3 on 2024-12-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchaseorder_requisitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='model_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
