# Generated by Django 5.1.3 on 2024-12-07 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_purchaseorderitem_brand_purchaseorderitem_model_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_delivery', 'Pending Delivery'), ('in_delivery', 'In Delivery'), ('awaiting_confirmation', 'Awaiting Manager Confirmation'), ('received', 'Received')], default='pending_delivery', max_length=30)),
                ('estimated_delivery_date', models.DateTimeField()),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('receipt_signature', models.ImageField(blank=True, null=True, upload_to='delivery_signatures/')),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to='delivery_photos/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='purchasing.purchaseorder')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delivered', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.delivery')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.purchaseorderitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
