# Generated by Django 5.1.4 on 2024-12-11 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0004_delivery_deliveryitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="delivery",
            old_name="actual_delivery_date",
            new_name="delivery_date",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="estimated_delivery_date",
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="actual_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="delivery_verification_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="delivery_verification_file",
            field=models.FileField(
                blank=True, null=True, upload_to="delivery_verifications/"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="delivery_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_deliveries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="receipt_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="delivery_receipts/"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="received_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_deliveries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_delivery", "Pending Delivery"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("verified", "Verified"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending_delivery",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_supplier", "Pending Supplier Approval"),
                    ("supplier_accepted", "Accepted by Supplier"),
                    ("supplier_rejected", "Rejected by Supplier"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
