# Generated by Django 5.1.4 on 2024-12-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "purchasing",
            "0005_rename_actual_delivery_date_delivery_delivery_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_supplier", "Pending Supplier Approval"),
                    ("supplier_accepted", "Accepted by Supplier"),
                    ("supplier_rejected", "Rejected by Supplier"),
                    ("confirmed", "Confirmed"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
