# Generated by Django 5.1.4 on 2024-12-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0006_alter_purchaseorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="delivery_confirmation_file",
            field=models.FileField(
                blank=True, null=True, upload_to="delivery_confirmations/"
            ),
        ),
    ]
