# Generated by Django 5.1.4 on 2024-12-12 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_globalsettings_inventoryitem_description_and_more"),
        (
            "purchasing",
            "0008_alter_delivery_status_alter_purchaseorder_supplier_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="warehouse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="inventory.warehouse",
            ),
        ),
    ]
