# Generated by Django 5.1.4 on 2024-12-12 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0009_delivery_warehouse"),
        ("requisition", "0021_alter_deliveryitem_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="requisition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_deliveries",
                to="requisition.requisition",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="source_type",
            field=models.CharField(
                choices=[("po", "Purchase Order"), ("requisition", "Requisition")],
                default="po",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="purchasing.purchaseorder",
            ),
        ),
    ]
