# Generated by Django 5.1.4 on 2024-12-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0010_delivery_requisition_delivery_source_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="brand",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="model_name",
            field=models.CharField(max_length=100),
        ),
    ]
