# Generated by Django 5.1.4 on 2024-12-13 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_globalsettings_inventoryitem_description_and_more"),
        ("purchasing", "0012_alter_delivery_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="receipt_signature",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="requisition",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="source_type",
        ),
        migrations.AlterField(
            model_name="delivery",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="purchasing.purchaseorder",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_deliveries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_delivery", "Pending Delivery"),
                    ("in_delivery", "In Delivery"),
                    ("pending_admin_confirmation", "Pending Admin Confirmation"),
                    ("verified", "Verified"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending_delivery",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="warehouse",
            field=models.ForeignKey(
                null=True,  # Keep it nullable for now
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.warehouse"
            ),
        ),
    ]
